services:
  - type: web
    name: sanjeevani-backend-api
    env: node
    plan: starter
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: rzp_test_TRlp6qdfVyCHyQ
      - key: RAZORPAY_KEY_SECRET
        value: Mg9ra16kSOpZfdlr2DqYTCks
      - key: MSG91_AUTH_KEY
        sync: false
